plugins {
    id 'com.android.application'
}

android {
    namespace 'com.suraj.levelchess'
    compileSdk 37

    defaultConfig {
        applicationId "com.suraj.levelchess"
        minSdk 23
        targetSdk 37
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
        }
    }
}
